using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

public class LanguageKeyExtractor: MonoBehaviour
{
    // CSV 파일이 있는 경로
    private static readonly string CSV_PATH = Path.Combine(Application.streamingAssetsPath);
    // 생성될 enum 스크립트가 저장될 경로
    private static readonly string ENUM_SCRIPT_PATH = Path.Combine(Application.dataPath, "02.Script/LanguageData/LanguageKeyDatas.cs");

    // 유니티 상단 메뉴에 "Tools/Generate Localization Keys" 메뉴를 추가
    [MenuItem("Tools/Generate Language Keys")]
    public static void GenerateKeysEnum()
    {
        // 1. 모든 CSV 파일에서 키 값들을 불러와 합친다.
        List<string> allKeys = new List<string>();
        string[] csvFiles = Directory.GetFiles(CSV_PATH, "*.csv");

        foreach (string filePath in csvFiles)
        {
            string[] lines = File.ReadAllLines(filePath);
            if (lines.Length <= 1) continue;

            for (int i = 1; i < lines.Length; i++)
            {
                if (string.IsNullOrEmpty(lines[i])) continue;

                string key = lines[i].Split(',')[0].Trim();
                if (!allKeys.Contains(key))
                {
                    allKeys.Add(key);
                }
            }
        }

        // 2. Enum C# 스크립트 파일 내용을 문자열로 생성한다.
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// This file is auto-generated by LocalizationKeyGenerator.cs. DO NOT EDIT.");
        sb.AppendLine("public enum LocalizationKeys");
        sb.AppendLine("{");

        foreach (string key in allKeys)
        {
            // 키 이름에 특수문자가 있을 경우를 대비하여 간단히 처리 (더 복잡한 규칙이 필요할 수 있음)
            string enumKey = key.Replace(" ", "").Replace(",", "");
            sb.AppendLine($"    {enumKey},");
        }

        sb.AppendLine("}");

        // 3. 최종적으로 스크립트 파일을 디스크에 쓴다.
        // 스크립트가 저장될 폴더가 없으면 생성
        Directory.CreateDirectory(Path.GetDirectoryName(ENUM_SCRIPT_PATH));
        File.WriteAllText(ENUM_SCRIPT_PATH, sb.ToString());

        // 4. 유니티 에디터가 새로운 스크립트를 인지하도록 에셋 데이터베이스를 새로고침한다.
        AssetDatabase.Refresh();

        Debug.Log($"LocalizationKeys.cs file generated successfully with {allKeys.Count} keys.");
    }
}
