using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEngine;
using UnityEditor;

public class PopUpEnumGenerator
{
    // 읽어올 JSON 파일 경로
    private static string JSON_PATH = Path.Combine(Application.streamingAssetsPath, "PopupData.json");
    // 생성될 Enum 파일 경로
    private static string ENUM_PATH = "Assets/02.Script/LanguageData/PopUpKeyDatas.cs";

    [MenuItem("Tools/Generate Popup Keys")]
    public static void Generate()
    {
        if (!File.Exists(JSON_PATH))
        {
            Debug.LogError("json 파일이 없습니다: " + JSON_PATH);
            return;
        }

        string jsonString = File.ReadAllText(JSON_PATH);
        // --- 2. 데이터 파싱 ---
        // 이전에 만든 PopupDataTable 클래스를 재사용합니다.
        PopupDataTable data = JsonUtility.FromJson<PopupDataTable>(jsonString);

        if (data == null || data.items == null)
        {
            Debug.LogError("JSON 데이터를 읽을 수 없습니다.");
            return;
        }

        // --- 3. Enum 코드 작성 (StringBuilder) ---
        StringBuilder sb = new StringBuilder();

        sb.AppendLine("// This file is auto-generated by PopupKeyGenerator. DO NOT EDIT.");
        sb.AppendLine("public enum PopupKey");
        sb.AppendLine("{");
        sb.AppendLine("    None = 0,"); // 기본값

        foreach (var item in data.items)
        {
            // 키가 비어있지 않은지 확인
            if (!string.IsNullOrEmpty(item.key))
            {
                // Enum 이름 규칙에 맞게 공백 등을 제거 (필요시 Regex 사용)
                string safeKey = item.key.Replace(" ", "_");
                sb.AppendLine($"    {safeKey},");
            }
        }

        sb.AppendLine("}");

        // --- 4. 파일 저장 ---
        // 저장할 폴더가 없으면 생성
        string dir = Path.GetDirectoryName(ENUM_PATH);
        if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);

        File.WriteAllText(ENUM_PATH, sb.ToString());

        // --- 5. 유니티 새로고침 (중요) ---
        // 이걸 해야 유니티가 방금 만든 파일을 인식해서 컴파일합니다.
        AssetDatabase.Refresh();

        Debug.Log($"PopupKey Enum 생성 완료! ({data.items.Count}개)");
    }
}
